version: "3.9"

# Network configurations for ShinyProxy service. Uncomment below code lines to create
# a user-defined network (disables auto-configured networks).
#networks:
#  rstudio-network-4.2.1:
#    name: rstudio-network-4.2.1

services:
  rstudio-server:
    # Define container name before building it.
    container_name: rstudio-4.3.0-texlive-full
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    # Use local images created using a dockerfile.
    image: dncr/rstudio-server:4.3.0-texlive-full
    # uncomment "build" section to create images from a docker file
    # build:
    #  context: ../
    #  dockerfile: dockerfiles/rstudio-server.Dockerfile
    # set restart policit for the container
    restart: "unless-stopped"
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Define environments.
    environment:
      # - USER=rstudio  # by default, the username is set "rstudio"
      - PASSWORD=rstudio**
      - ROOT=TRUE
    # Select an empty port for the container.
    ports:
      - '8000:8787'
    volumes:
      # Set external volumes.
      # User-specific container (external volume). Files in this folder will be stored as an external volume
      # out of docker container. If docker container was removed, external files will be remained in the main 
      # computer. Multiple volumes can be defined.
      # - '/home/bio/Containers/dncr:/home/rstudio/externalvolume/Container'
      # - '/home/SharedFolder:/home/rstudio/externalvolume/SharedFolder'
      # - ../externalvolume:/home/rstudio/externalvolume
        - /home/dncr:/home/rstudio/externalvolume
        - /media/dncr:/home/rstudio/externalmedia
    #networks:
    #  - rstudio-network-4.2.1
