services:
  rstudio-mlseq:
    container_name: mlseq-devel
    image: dncr/rstudio-server:mlseq-devel-4.1.1
    build:
      context: ../
      dockerfile: dockerfiles/rstudio-mlseq.Dockerfile
    restart: "unless-stopped"
    user: 'root'
    profiles:
      - mlseq
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    # Select an empty port for the container.
    ports:
      - '8001:8787'
    command: ["--privileged"]
    # volumes:
    #   - '/home/dncr/GitHub/MLSeq:/home/rstudio/externalvolume/MLSeq'
