services:
  r-base:
    image: dncr/r-base:multi-arch
    build:
      context: ../
      dockerfile: dockerfiles/multi-arch.Dockerfile
      args:
        - R_VERSION=${R_VERSION}
        - R_HOME=${R_HOME}
        - TZ=${TZ}
        - CRAN=${CRAN}
        - LANG=${LANG_SET}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - DOCKER_HUB_REPO=${DOCKER_HUB_REPO}
      platforms:
        - linux/arm64/v8
        - linux/amd64

