
name: rstudio-tmp

# Network configurations for ShinyProxy service. Uncomment below code lines to create
# a user-defined network (disables auto-configured networks).
#networks:
#  rstudio-network-4.2.1:
#    name: rstudio-network-4.2.1

services:
  rstudio-server:
    # Define container name before building it.
    container_name: rstudio-tmp
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    # Use local images created using a dockerfile.
    image: dncr/rstudio-server:${R_VERSION}-${UBUNTU_VERSION}
    env_file:
      - .env
    # Define extra environments not specified in "env_file".
    # Export RSTUDIO_PASSWORD before running compose (e.g., `export RSTUDIO_PASSWORD=...`)
    # so the container picks it up without hard-coding credentials in this file.
    environment:
      # - USER=rstudio  # by default, the username is set "rstudio"
      - PASSWORD=${RSTUDIO_PASSWORD:?Set RSTUDIO_PASSWORD in your shell before running docker compose}
    # set restart policit for the container
    restart: "unless-stopped"
    # Run as the unprivileged default user. Switch to root only if a specific workflow requires it.
    user: 'root'
    # Select an empty port for the container.
    ports:
      - '8005:8787'
      # Map a host SSH port to the container's sshd (set the host side as needed, e.g., 2222).
      - '2222:22'
    volumes:
      # Bind mounts are optional. Uncomment and point to a valid host path if you want to persist workspaces.
      - '/Users/dncr:/home/rstudio/externalvolume'
      # Mount your public key to authorize SSH sessions (update the host path).
      - ~/.ssh/id_ed25519.pub:/home/rstudio/.ssh/authorized_keys:ro
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "1.0"  # Set the fraction of CPU cores (0.5 means half of a core)
    #      memory: 32G  # Set the memory limit (e.g., 512 megabytes)
    #networks:
    #  - rstudio-network-4.2.1
